name: "Releases"

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set node version
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install
      run: |
        npm install
        npm run setheapsize

    - name: Lint
      run: npx grunt lint

#     - name: Unit Tests
#       run: |
#         npm test
#         npm run testnodeconsumer

    - name: Production Build
      if: success()
      run: npx grunt prod

    # - name: UI Tests
    #   if: success()
    #   run: xvfb-run --server-args="-screen 0 1200x800x24" npx grunt testui

    - name: Upload Release Assets
      if: success()
      id: upload-release-assets
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/prod/*.zip
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
        body: "详情请参考CyberChef原版[CHANGELOG](https://github.com/gchq/CyberChef/blob/master/CHANGELOG.md)和[commit messages](https://github.com/gchq/CyberChef/commits/master)。"

#     - name: Publish to NPM
#       if: success()
#       uses: JS-DevTools/npm-publish@v1
#       with:
#         token: ${{ secrets.NPM_TOKEN }}

    - name: Docker Login
      if: success()
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.2.1
      
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        # Path to the Dockerfile
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/srk-toolbox:latest
